# Generated by Django 3.0.8 on 2020-07-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200724_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='text',
            new_name='About',
        ),
    ]
