# Generated by Django 3.0.8 on 2020-07-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200724_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='enddate',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='startdate',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
