# Generated by Django 3.0.8 on 2020-07-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_portfolio_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='Name',
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='experience',
            field=models.CharField(max_length=15),
        ),
    ]
