# Generated by Django 3.0.8 on 2020-07-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20200724_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=30)),
            ],
        ),
    ]
