# Generated by Django 3.0.8 on 2020-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('info', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
