# Generated by Django 3.0.8 on 2020-07-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20200726_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codeused',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
