# Generated by Django 3.0.8 on 2020-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20200727_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='info',
            field=models.CharField(max_length=450),
        ),
    ]
